version: '3'

services:
  server:
    build: .
    ports: 
      - "8000:8000"
  db:
    image: 'ash3rr/my-postgres-db:1.3'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  data: